package de.fu_berlin.imp.seqan.usability_analyzer.srv.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;

public class EntityViewer extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Table table_1;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public EntityViewer() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		/* Create the table with a caption. */
		table_1 = new Table("This is my Table");

		/*
		 * Define the names and data types of columns. The "default value"
		 * parameter is meaningless here.
		 */
		table_1.addContainerProperty("First Name", String.class, null);
		table_1.addContainerProperty("Last Name", String.class, null);
		table_1.addContainerProperty("Year", Integer.class, null);

		/* Add a few items in the table. */
		table_1.addItem(new Object[] { "Nicolaus", "Copernicus",
				new Integer(1473) }, new Integer(1));
		table_1.addItem(new Object[] { "Tycho", "Brahe", new Integer(1546) },
				new Integer(2));
		table_1.addItem(
				new Object[] { "Giordano", "Bruno", new Integer(1548) },
				new Integer(3));
		table_1.addItem(
				new Object[] { "Galileo", "Galilei", new Integer(1564) },
				new Integer(4));
		table_1.addItem(
				new Object[] { "Johannes", "Kepler", new Integer(1571) },
				new Integer(5));
		table_1.addItem(new Object[] { "Isaac", "Newton", new Integer(1643) },
				new Integer(6));
		table_1.requestRepaintAll();
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("100.0%");
		table_1.setHeight("100.0%");
		mainLayout.addComponent(table_1,
				"top:0.0px;right:0.0px;bottom:0.0px;left:0.0px;");

		return mainLayout;
	}

}
